version: "3.9"
services:
  spring-api-image:
    image: ms-account-banks
    container_name: ms-account-banks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - spring-network

networks:
  spring-network:
#volumes:
#  mysql-volume: